language: java
install: true
matrix:
  include:
  - jdk: oraclejdk8
script: gradle build dist
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cGJ7GW90FRuqVcSk9OLuHmwUE346/YlM5AiH24FKQbVXPFYfHojMOHMnyPWmw7OeDC1GcusZBI9LnH4XAgj9nq4cSGbZwMYDaMIbj6yU7gZ2xbDCUyxX4gJdic9Ic/qZ4X0s7HTRUHxtk8a+btUgr4RW8AhnDzVZHDtzNTqguww=
  file:
    - "dist"
  on:
    tags: true
    all_branches: true
