language: java

install: true

matrix:
  include:
  - jdk: oraclejdk8

script:
  - gradle clean build
  - gradle dist

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/RlonRyan/JBasicX --tags
  - ls -R

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cGJ7GW90FRuqVcSk9OLuHmwUE346/YlM5AiH24FKQbVXPFYfHojMOHMnyPWmw7OeDC1GcusZBI9LnH4XAgj9nq4cSGbZwMYDaMIbj6yU7gZ2xbDCUyxX4gJdic9Ic/qZ4X0s7HTRUHxtk8a+btUgr4RW8AhnDzVZHDtzNTqguww=
  file:
    - "README.md"
    - "dist/JBasicX-Main-0.1.0.zip"
    - "dist/JBasicX-Test Output-0.1.0.zip"
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-[0-9]/

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.esper.net#RlonRyan"
    on_success: always
    on_failure: always

env:
  global:
    secure: aRAJTA8NZKmuSBsSFhQidZIwo9/2n4KPUZX/gcz/1ckqjCv9m+j71t73CQ2gdGcDlYrJS/0w7p80R7PHz7N1IQrXNn4lSRKqukhvqFmGqac1Fjol/8oLdY8/uAiArfgL43iG8FZmPTiKghLjGPiSX/OihbIUKkkixeLGFIXDZK0=
