language: java

install: true

matrix:
  include:
  - jdk: oraclejdk8

script:
- gradle clean build
- gradle dist

before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$GITPERM@github.com/RlonRyan/JBasicX --tags
- ls -R

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITPERM
  file:
  - README.md
  - dist/JBasicX-Main-0.1.0.zip
  - dist/JBasicX-Test Output-0.1.0.zip
  on:
    tags: false
    all_branches: true

branches:
  except:
  - /^*-v[0-9]/

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
    - irc.esper.net#RlonRyan
    on_success: always
    on_failure: always

env:
  global:
    secure: KKAzDZFyDJu0Tzl+L6DGXezqen8OTiRkGsnzgvGgLyZP3nPonIUdakPoyMLodUuOQnJsnnO0UnGrH484bZuAsmBb/yW00naZQgyamdHAApvbnRtmfxfcmG52sfdxecZO0D6/DshJIVN6gvMRsJoBPYGoooEwc3wdO1rPfI2cZ44=
